spring:
  datasource:
    username: root
    password: qwertyuiop123
    url: jdbc:mysql://localhost:3306/big_event?serverTimezone=Asia/Shanghai&useSSL=false&useServerPrepStmts=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名,表名下划线后面的字母变成大写，对应实体类的名字