spring:
  datasource:
    username: root
    password: qwertyuiop123
    url: jdbc:mysql://localhost:3306/big_event?serverTimezone=Asia/Shanghai&useSSL=false&useServerPrepStmts=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver